### ISSUE TITLE
How do I keep listening to the clipboard?

### ISSUE THREAD

**Issue by Vzz1c** [DoumanAsh/clipboard-win#37]
How do I keep listening to the clipboard? I'm using Monitor, but I'm having a problem with it, I'm getting an error about continuously listening to the clipboard in multiple threads because it's not safe, and I'm seeing a function related to this problem, shutdown_channel(), but I don't understand how to use it.

**Comment by Vzz1c** [comment]
I use  `tokio`

**Comment by DoumanAsh** [comment]
You do not need to listen it on multiple threads and you cannot because it requires exclusive access to it

So ideally you create thread, start monitor and listen for all messages by continuously calling [Monitor::recv](https://docs.rs/clipboard-win/5.4.0/clipboard_win/monitor/struct.Monitor.html#method.recv)

Upon encountering message you can read clipboard and send data over channel to worker that wants to consume message

This is pretty low level interface so it is hard to say how you should use it as it depends on your use case

I have alternatively a more simple and callback based library for cross platform
https://crates.io/crates/clipboard-master/4.0.0-beta.6

**Comment by Vzz1c** [comment]
Unable to call asynchronous functions in `on_clipboard_change`

**Comment by DoumanAsh** [comment]
Clipboard API itself cannot be asynchronous 
So you need to use channels https://docs.rs/tokio/1.40.0/tokio/sync/mpsc/index.html or some other primitives to communicate with your async code
